import Account from "@/components/Account";
import { Text, VStack } from "@chakra-ui/react";
import { Delius } from "@next/font/google";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import Head from "next/head";
import Image from "next/image";

// const inter = Inter({ subsets: ["latin"] });
const delius = Delius({ weight: "400", subsets: ["latin"] });

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={delius.className}>
     
          {!session ? (
            <VStack mx='4' pt='16'>
              <Image
                alt='aaua logo'
                src='/aaua_logo.png'
                width={100}
                height={100}
              />
              <Text px='6' fontWeight='bold' fontSize='2xl'>
                AAUA REQUEST PORTAL
              </Text>                        
                <Text fontSize='sm'>(Student / Staff)</Text>
              <Auth
                supabaseClient={supabase}
                appearance={{ theme: ThemeSupa }}
                theme='dark'
              />
            </VStack>
          ) : (
            // <p>Account page will go here.</p>
            // <MainEntry />
            <Account session={session} />
          )}
       
      </main>
    </>
  );
}
